### PR TITLE
Correct repo URL in package.json

### PR DESCRIPTION
**Pull request by mef**

### CODE REVIEW

**Comment by IdoO2** [comment]
Hi there,
Are you sure you’re PRing to the right repo? This is a very old fork.

**Comment by mef** [comment]
My mistake, I assumed that this repository corresponds to the package published on npm (which points to  404 page on github).

Is your version of `npm-scripts-watcher` published on npm, by any chance?

**Comment by IdoO2** [comment]
Unfortunately not, I don’t even remember what lead me to fork this. Probably you should check with the creators at https://github.com/wehkamp... or fork the fork :-)

**Comment by mef** [comment]
Thanks. I guess I'll just look for another package doing the same thing...

**Pull request closed without merging**
